---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1qqz7jesquceqwqea6tz6gc0fac37m95vf9gqpqzmdlanemwq8czq95p4ka
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1qqz7jesquceqwqea6tz6gc0fac37m95vf9gqpqzmdlanemwq8czq95p4ka
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1qqz7jesquceqwqea6tz6gc0fac37m95vf9gqpqzmdlanemwq8czq95p4ka
