kind: ENC[AES256_GCM,data:PKOi3ch0,iv:I064OuJfbVkEgsXzP32aZKvT82KBAPuLUkwPbmhiThA=,tag:UtwEFAdfoy/rwN9nfdsoyQ==,type:str]
ansible_user: ENC[AES256_GCM,data:bas+Og==,iv:+2n46NfuJN6xG8tHcjUkkGIpmZk1Htk5HZJvzyi6rP0=,tag:hBZ3l4JfsVrIKnsoJl7A2Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:XhKS7iAoRFs=,iv:h0lniTM1p+yvqekL1Xies7gZrd3c+ynmQXmGJ9LPnUc=,tag:+bUNQpCQQdg71uqm33sxyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqz7jesquceqwqea6tz6gc0fac37m95vf9gqpqzmdlanemwq8czq95p4ka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFaXFJV3pCNVFGUjV2Ym05
            YUx0L3krUnpCYzZXSmhZQWRQejVZTFRQQVFNCitJU0E0SjdsU0VHTGpUNDBlbGx6
            VHBNTlg2OTJrQ2VjbW5CeFVuTzJWTlkKLS0tIDkwdHpkYzNnejFIL2VJbHFJQlVC
            U1R0aHBRdkdFV0YwaytvODRGcUhHV1kKd0mVHkWQzwFLZsDpN9JqVS9N3XeSxJRn
            qRiDo5s9S9HFFvsSlEltDCOyDdgWJylZSnXZKZIsw/20gUrsGUSmWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-21T16:17:17Z"
    mac: ENC[AES256_GCM,data:iFygoqMdF5wBuHFeaubzM9zB5cjbxYgjNT8jKEhaoG0LOGIQMk71CMEAkAc+TDaQo7MwDijOpda3UM0oVKUzB+uoHvM/DlRtKAOMTHCl6n4VJr/dPfpsMfMFsa8uW3txrxO3F272bDeAp1KWuMHLGoFn9VoKTTkESMRnpWzDraE=,iv:UTM7e72m/JOfjQd0pm+O+Eepq3mydqAmOLkhOr5Q1fw=,tag:90lKNIjCHjRrAX/iKzRPow==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
