apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:NKW8LNL6xa1FlSCTEPIIioaOsdhNvlH8lp8yEqDTfjNH88pWllZWUw==,iv:UTw053KP5iQyBdao/qQBzBPHxehGh+FLp6bl9feYdW4=,tag:m6en3HZwTQgDOj+YmwtB6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqz7jesquceqwqea6tz6gc0fac37m95vf9gqpqzmdlanemwq8czq95p4ka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMmJldmc3NWp5ei9FbHJY
            ZER2U1FocGg1aW93dHVDak5hRXhVL29JV0hFClluaTFsT3lTVnNPVWQrSnQrbW1K
            K3NvM1l2Z21DWEZCa0NhdEZxQVFXbFkKLS0tIEpRZnJWWWFibnpDVkttZCtRU1kw
            cWpqOGN5Mkt5eVZ1ODJzREFuUWJrYlkKJwEksUPAFnolE6fnpxoYq+LOtRl2oMrc
            gjKuqXKJUXYBw22GwHAXotgQWIoQoa5oxuWSZhgTjc62KRW9nSwKCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-21T16:17:17Z"
    mac: ENC[AES256_GCM,data:4Vp2sZFDyDTh8JJDjhcj+2PjAm1O12O1KrDatM4rJIg8OeQb0Wxog8VZwfx1AjvLTTwgiwaDwGYTf0f6Fzn+7KfiwvMaOAJxaM5S4JFd/Zw59kRh0OoIqSQM9nGenyzYe1DZygDdEUYFPsI+4TUOb0n/gLPIe3F/OKR26/K+GSg=,iv:zAeuxd91YGFuZjmT8Zpmdg5l2BkXrRoX+XI1Nolu/+g=,tag:faif1Wo7gYZnm6BemqgcAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
