apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:tbx17kmrvIoXQRKQHL30c2S0kmBV3jc8MQ17DO5HVIjA/QJVPw==,iv:ZV31CFjBH4U0WFurkuuZ3HoqAbMM+bSRcWyQm8By2pw=,tag:tnC98z05KHmwjfNC0GxkFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqz7jesquceqwqea6tz6gc0fac37m95vf9gqpqzmdlanemwq8czq95p4ka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBma3ZOc0V4cmx3VGxxRG5r
            S0xDbS81aGMybUZvTEtOZ2lSbDQ4b09NY1g0ClNLcGJYS2VTVVVobzFNUEVGZUJT
            NGprZkdDNkdFSlNNZ3Q3OHpvT1IvZncKLS0tIHFhR3lqTDlEMm83Z28zV0J4VXNQ
            amNONnh2SjkwTkQ5WWQrZnZxOVhiWmMKDrbzxsG1HgHEMV6L+8gNPBW5BxoiA+U2
            MEknNki9scjcfs98OaAmMQNcANq5QvOqVQqA2X5ejQNj/Swa5kVkKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-24T16:31:23Z"
    mac: ENC[AES256_GCM,data:GsCvaiKmbX9WyJQlzeOJkdY/b5pjCTXag77ayS3dWK8N8ejrMoxWpzF9QHUHVgZyMIh9zw1NuAEMHBoz4Jdb2vqMkkSNGqVOUCV+izVi/Ac5NqshAHRKv1m+HyHzq0jOkOMIjuR1HE4fp3Pxq1Rfr8h3+jKx1BQQG1Jd03nFRbc=,iv:yGmNvxGz2HQwJ2kWsOwX+CywEDjEgawBNDVUoxJIq5k=,tag:yiMN4LbQIex7fyr2gR+ZXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
