apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:F2q66Fm3PH0Aa9oVSdEGfzvo0VosORtp2Q==,iv:QujMDaBW/E1XvgxrdR4y9lsN4RHVs8yYy8cyVa9VkjE=,tag:kKYF7bu700wQLipuTqZL2g==,type:str]
    api-key: ENC[AES256_GCM,data:vbgsAQGDp1b+V4C44hslubWFF/QGQSI4dBybQrgXn8qlHonz2g==,iv:gVJXOGtC4eBiTJ3Yr0r0sEEzaA1JQ34ngES8IwbI+zg=,tag:qzWtKojAJy+iMcPDWeGU/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqz7jesquceqwqea6tz6gc0fac37m95vf9gqpqzmdlanemwq8czq95p4ka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZGpWV3g1c29ETHpqYkFq
            TW9LeUd1elB1Zk54NXl1VjJyVmxBaFRHMGdnCkVmdEJleHc5ZUYvSHlmbklqaGlN
            dVVBRnZLMEtza2lZWnBPK1c2WFhsbzgKLS0tIG1uUytHZllJNXBWQWMyUWtTZzJx
            dzc3ZE1HRzJuMmgxcHo3bTJWNDN6ZjAKt8Mkd2gytOy9evxtYGR0mkSWL3kUMSUV
            69Atfg2tq3rDQQHWOM14QA45oxdNY+3h/JCtCZv0M1qrdLvOnl9rNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-21T16:17:17Z"
    mac: ENC[AES256_GCM,data:At99ectknh41m7IWo/lOMn1zqiWBPVsPEMsnULUo8KYMf9/FuwuqNSyikwb3FLlixupjwoKDnBrUP9VyXws3Qpvy/X/MzdfURZ81mISm47xt/XWfKDVlse0luhjv4k9uoudOIs9F6ofNR3ccFDKxcRjKp8EvvV2uj22sRITu+7c=,iv:RvY5bsFiTo++O2x40Ab6jMrDF87OlXtb4DKgU7WrxtM=,tag:Xi7H/SBJnIz4RFM9Y2ULQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
