apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:CqNJIGTXgC5dtJ2n01SE4K4sWvP4aF/ezg==,iv:k0zdXjISGz2MAEIC8xqUPOj/VlhGg769WRw0kJWpx8o=,tag:uflUop17Q4+X7ysKL/AJWg==,type:str]
    api-key: ENC[AES256_GCM,data:GA87ShxDZ2q7cFbh0qlg05sag27b8EbWv1q7U3o/UQ3zCaPsAg==,iv:wlggm0DiMl+qmvQCnx4ziAtgZWJ4KF+KNlB7UrD3I3o=,tag:Dxc1cqF3iFaRFD8NVvbj4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqz7jesquceqwqea6tz6gc0fac37m95vf9gqpqzmdlanemwq8czq95p4ka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZTB1d1FHWlhSWHorUytJ
            QjFaQk5YKzZuNHNZUEpobytMUUNSV3A2bnk4CnYxUGVPUlNZVUZmUGhuL04wMW9n
            aVFMVVBjREtYaVFIL3ZKVTdwa3lJSG8KLS0tIHhIdlBJSThYaCtuV2NBaUdibTlt
            VWZaZ1ZLRk5CQWRaNVBqN1MwVGVXUHMKjjEr1ZVQMTqFP9Bw+ZonF8LiKL3mPv3a
            FsCIhM+SgOCjGpGpkpIa3PgJ3q9+kBhl/p7uFEidwnKkKzvq/v+VmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-24T16:31:23Z"
    mac: ENC[AES256_GCM,data:r7xzNXagSSSjZqYGbCk1sbBvrsZAKLZd/TLkvx7qt7IgnkpOr3jOUDED7OXTwYVDY2Nz8VMzkiLEm7x7K1408o/RZ5GccK2SU80T/OuL6CmCcuqJko1VUmZPQgamj9BkILb1xv7uLLB2oK/zWZoeJXaPr3r46L0JmPKPDlgsPfk=,iv:kqAECHj62XeYej9HnCAGTuHB85yaxzXJPNKbAltKCzQ=,tag:nmrYTO5Hj54hu7tVpYC9IQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
