apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:SJGwtMDEFXo2IJOGFUUOQV0/aCogP+wwTZqLUsNd/vOx3E6LnUfenvugakaa8aXIBF7Y0FzOlWuZFeKx,iv:6w5s/m2+1F3Gvv3GPy41Dfd3ju/+XzqTFSt/2UPRqLw=,tag:r1m2dp4BoNsjj+LcccOrdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqz7jesquceqwqea6tz6gc0fac37m95vf9gqpqzmdlanemwq8czq95p4ka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcEFqc0twOElTV0F5S1NQ
            eXFlOWI5czBaWkNPbEdFV250aGRNTkhOdldjClM1cjRmZFBmcElQSUxMQUJzQ2ZW
            WFAwNzRheXhEMFR3QkkvajV4d2xKMFUKLS0tIG9rR2twMk5oeUdqOWFtNkYzWXJR
            UEEzdmRzOWxLeVQzeCtxT2xlSi9YNzgKalS1gjrb4f90Ojhb6k43TmsL1hIGKu0d
            77hiVlOE0AgdQX11km6YIpqGgoZLPkyccvL85bBB78JOeZQe70BDMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-21T16:17:17Z"
    mac: ENC[AES256_GCM,data:qGADLXNqjrhWAv1APdm1rpgOxUxoWy/vquHo8D8hUlAVYGNPEO+pAhmxyDVkYdp9fei1e/lnlrcsrBAre0l4fkc+KAgGWUSNUdfGQww/FCMWaZwqH+CVwP4r2K5gc9OAlwYh9ELq6Fv1scU6mzPnkLuo/Yj1kCZS79a2wwHQAhs=,iv:TXdF8Yz9CcF50SVb5jzWB8OY/oHZpoN2t7NpFqAGM4M=,tag:gcnnwgkltrKqX2u7uEQITw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
