apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:kESOXjJshVMT5YkvQ21WxUX3u8TgCt7yUu4bVPRYpVDRCWravj7XteTnDOq0P4RdFqp4N3u0lhb0lYeP,iv:mfd+5pVwV00XdwFE4SWpvvSJ7cT9bjf136uGw/uPt+E=,tag:Jy7kBuUcKsLsVKNXuXcJlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqz7jesquceqwqea6tz6gc0fac37m95vf9gqpqzmdlanemwq8czq95p4ka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZR3AvNEM1U1lYNnpNYnNJ
            cTIxZ3JHa3h2Z245TTFDcElIc0p0TDBVa0Y4CkhLYXUwU0tDUHppbkIrbVk4L1c3
            RUg0SkJ2VWY2OGpLZEhpeCtnRnFldlkKLS0tIDlmekNVMGRTV1I2bURqSkN6T3NN
            VmRPa2NiR3A0TzdMdHVobEcyUm5VamsKgJkgNpSbcKiS8aTh1VELbQZSM/oFOC+D
            64sY/E0Unu4Jyv7K5FUdFL0I4yKZpLVEUUZARIQsJ1RyctNmRCHimQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-21T16:23:30Z"
    mac: ENC[AES256_GCM,data:gvSZxrTolhyD9wtHAh3JxlQ6ZAwuPpUL2ZwQonvB2u7Rnp22F+i/lifk7RlfBIfJhZgK4HxnFEBp+2POTkHcbIuXVW1Fc57ZOklh0X1PdF2SoiWDxnEpE4qGKp6mPvKIYLv5yHru3ohxGBOWaL3w3DRxKgGCYx256HtXnceQxww=,iv:6GUSxA/gILdtX1BudEjpcosWl9dKjG/5BDuRhV9UEkg=,tag:0ktEYYOkyY5XMcHKuJ4SzA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
