apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:DjT/x2guhlswRouCJq57,iv:va1xd5nZhsJa7GwYqPBoNqsIkqlRCTWslCrPVXwS9B0=,tag:dy1TV24c1bCD/FfyH9sa0w==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:g9ChV45PMAAjZiJPicxZrKYK4JicoPur+g==,iv:5kPImyhTX08rLP/6JTXqHmzsvuULasqg9zm0e6UVV8w=,tag:3eGwpQrEG6oSG41Sxlw1vw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqz7jesquceqwqea6tz6gc0fac37m95vf9gqpqzmdlanemwq8czq95p4ka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWDVYQjdWaXQ5b3NkeEtD
            Q3U3NVdPQ0FIQ0JvdkVodEVtSnA1dTV3UFdnCnNxTWpya0hmbDZhRUptUjFDL1ZJ
            THZ0RG82UklWMnMwZEI4ZTZOL2JuK1UKLS0tIGhLQ3h5VXRrc0NJNklsNSt5R201
            dGFjenhmNUE0R3RQbW9UdTRMamoxcncK8CEQbG2SyLBGO9zHSvM6gduzX3coDUOs
            kK7n0gX9YeSkfrJTdY0JLI8ZK7L4xi+oYoulLwS/c3wQTIgx9Lcpsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-20T20:32:24Z"
    mac: ENC[AES256_GCM,data:1s/eazDJF+rYjqVrYVqVc1sQ5I5R9aV2HmUkStwfDqcmnNVl0b5Z2ga0zrERGTedB65rpgaOgA5UWSBOndpX7Yvoulce20p4ZZWh81loL00g69wqB4TI1Q222lh0UsqPqeJ4VzY4zq5yjU3ZzcIjLrvqkh3ZwAhMI6dzLAzfVds=,iv:pYek65dypk6acl9SQcaVqTGn5IMH9TeIgMGG+2sszh8=,tag:64iLFmckkaqzeRCk/iErVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
