---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Buenos_Aires"
  KUBE_VIP_ADDR: "192.168.2.232"
  METALLB_LB_RANGE: "192.168.2.230-192.168.2.231"
  METALLB_K8S_GATEWAY_ADDR: "192.168.2.230"
  METALLB_INGRESS_ADDR: "192.168.2.231"
